// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: store/api.proto

package store

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StoreService_CreateAccount_FullMethodName          = "/backend.store.api.StoreService/CreateAccount"
	StoreService_Reset_FullMethodName                  = "/backend.store.api.StoreService/Reset"
	StoreService_Credit_FullMethodName                 = "/backend.store.api.StoreService/Credit"
	StoreService_Debit_FullMethodName                  = "/backend.store.api.StoreService/Debit"
	StoreService_GetUserBalance_FullMethodName         = "/backend.store.api.StoreService/GetUserBalance"
	StoreService_CheckTransaction_FullMethodName       = "/backend.store.api.StoreService/CheckTransaction"
	StoreService_StreamBatchTransaction_FullMethodName = "/backend.store.api.StoreService/StreamBatchTransaction"
	StoreService_StreamTransaction_FullMethodName      = "/backend.store.api.StoreService/StreamTransaction"
	StoreService_ListBalance_FullMethodName            = "/backend.store.api.StoreService/ListBalance"
	StoreService_StreamCheckTransaction_FullMethodName = "/backend.store.api.StoreService/StreamCheckTransaction"
	StoreService_SendBatchTransaction_FullMethodName   = "/backend.store.api.StoreService/SendBatchTransaction"
)

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreServiceClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Credit(ctx context.Context, in *CreditRequest, opts ...grpc.CallOption) (*CreditResponse, error)
	Debit(ctx context.Context, in *DebitRequest, opts ...grpc.CallOption) (*DebitResponse, error)
	GetUserBalance(ctx context.Context, in *GetUserBalanceRequest, opts ...grpc.CallOption) (*GetUserBalanceResponse, error)
	CheckTransaction(ctx context.Context, in *CheckTransactionRequest, opts ...grpc.CallOption) (*CheckTransactionResponse, error)
	StreamBatchTransaction(ctx context.Context, opts ...grpc.CallOption) (StoreService_StreamBatchTransactionClient, error)
	StreamTransaction(ctx context.Context, opts ...grpc.CallOption) (StoreService_StreamTransactionClient, error)
	ListBalance(ctx context.Context, in *ListBalanceRequest, opts ...grpc.CallOption) (*ListBalanceResponse, error)
	StreamCheckTransaction(ctx context.Context, opts ...grpc.CallOption) (StoreService_StreamCheckTransactionClient, error)
	SendBatchTransaction(ctx context.Context, in *SendBatchTransactionRequest, opts ...grpc.CallOption) (*SendBatchTransactionResponse, error)
}

type storeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreServiceClient(cc grpc.ClientConnInterface) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StoreService_CreateAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StoreService_Reset_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) Credit(ctx context.Context, in *CreditRequest, opts ...grpc.CallOption) (*CreditResponse, error) {
	out := new(CreditResponse)
	err := c.cc.Invoke(ctx, StoreService_Credit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) Debit(ctx context.Context, in *DebitRequest, opts ...grpc.CallOption) (*DebitResponse, error) {
	out := new(DebitResponse)
	err := c.cc.Invoke(ctx, StoreService_Debit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetUserBalance(ctx context.Context, in *GetUserBalanceRequest, opts ...grpc.CallOption) (*GetUserBalanceResponse, error) {
	out := new(GetUserBalanceResponse)
	err := c.cc.Invoke(ctx, StoreService_GetUserBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) CheckTransaction(ctx context.Context, in *CheckTransactionRequest, opts ...grpc.CallOption) (*CheckTransactionResponse, error) {
	out := new(CheckTransactionResponse)
	err := c.cc.Invoke(ctx, StoreService_CheckTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) StreamBatchTransaction(ctx context.Context, opts ...grpc.CallOption) (StoreService_StreamBatchTransactionClient, error) {
	stream, err := c.cc.NewStream(ctx, &StoreService_ServiceDesc.Streams[0], StoreService_StreamBatchTransaction_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &storeServiceStreamBatchTransactionClient{stream}
	return x, nil
}

type StoreService_StreamBatchTransactionClient interface {
	Send(*StreamBatchTransactionRequest) error
	Recv() (*StreamBatchTransactionResponse, error)
	grpc.ClientStream
}

type storeServiceStreamBatchTransactionClient struct {
	grpc.ClientStream
}

func (x *storeServiceStreamBatchTransactionClient) Send(m *StreamBatchTransactionRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storeServiceStreamBatchTransactionClient) Recv() (*StreamBatchTransactionResponse, error) {
	m := new(StreamBatchTransactionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storeServiceClient) StreamTransaction(ctx context.Context, opts ...grpc.CallOption) (StoreService_StreamTransactionClient, error) {
	stream, err := c.cc.NewStream(ctx, &StoreService_ServiceDesc.Streams[1], StoreService_StreamTransaction_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &storeServiceStreamTransactionClient{stream}
	return x, nil
}

type StoreService_StreamTransactionClient interface {
	Send(*StreamTransactionRequest) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type storeServiceStreamTransactionClient struct {
	grpc.ClientStream
}

func (x *storeServiceStreamTransactionClient) Send(m *StreamTransactionRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storeServiceStreamTransactionClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storeServiceClient) ListBalance(ctx context.Context, in *ListBalanceRequest, opts ...grpc.CallOption) (*ListBalanceResponse, error) {
	out := new(ListBalanceResponse)
	err := c.cc.Invoke(ctx, StoreService_ListBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) StreamCheckTransaction(ctx context.Context, opts ...grpc.CallOption) (StoreService_StreamCheckTransactionClient, error) {
	stream, err := c.cc.NewStream(ctx, &StoreService_ServiceDesc.Streams[2], StoreService_StreamCheckTransaction_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &storeServiceStreamCheckTransactionClient{stream}
	return x, nil
}

type StoreService_StreamCheckTransactionClient interface {
	Send(*StreamCheckTransactionRequest) error
	Recv() (*StreamCheckTransactionResponse, error)
	grpc.ClientStream
}

type storeServiceStreamCheckTransactionClient struct {
	grpc.ClientStream
}

func (x *storeServiceStreamCheckTransactionClient) Send(m *StreamCheckTransactionRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storeServiceStreamCheckTransactionClient) Recv() (*StreamCheckTransactionResponse, error) {
	m := new(StreamCheckTransactionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storeServiceClient) SendBatchTransaction(ctx context.Context, in *SendBatchTransactionRequest, opts ...grpc.CallOption) (*SendBatchTransactionResponse, error) {
	out := new(SendBatchTransactionResponse)
	err := c.cc.Invoke(ctx, StoreService_SendBatchTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceServer is the server API for StoreService service.
// All implementations must embed UnimplementedStoreServiceServer
// for forward compatibility
type StoreServiceServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*emptypb.Empty, error)
	Reset(context.Context, *ResetRequest) (*emptypb.Empty, error)
	Credit(context.Context, *CreditRequest) (*CreditResponse, error)
	Debit(context.Context, *DebitRequest) (*DebitResponse, error)
	GetUserBalance(context.Context, *GetUserBalanceRequest) (*GetUserBalanceResponse, error)
	CheckTransaction(context.Context, *CheckTransactionRequest) (*CheckTransactionResponse, error)
	StreamBatchTransaction(StoreService_StreamBatchTransactionServer) error
	StreamTransaction(StoreService_StreamTransactionServer) error
	ListBalance(context.Context, *ListBalanceRequest) (*ListBalanceResponse, error)
	StreamCheckTransaction(StoreService_StreamCheckTransactionServer) error
	SendBatchTransaction(context.Context, *SendBatchTransactionRequest) (*SendBatchTransactionResponse, error)
	mustEmbedUnimplementedStoreServiceServer()
}

// UnimplementedStoreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStoreServiceServer struct {
}

func (UnimplementedStoreServiceServer) CreateAccount(context.Context, *CreateAccountRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedStoreServiceServer) Reset(context.Context, *ResetRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedStoreServiceServer) Credit(context.Context, *CreditRequest) (*CreditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Credit not implemented")
}
func (UnimplementedStoreServiceServer) Debit(context.Context, *DebitRequest) (*DebitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Debit not implemented")
}
func (UnimplementedStoreServiceServer) GetUserBalance(context.Context, *GetUserBalanceRequest) (*GetUserBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBalance not implemented")
}
func (UnimplementedStoreServiceServer) CheckTransaction(context.Context, *CheckTransactionRequest) (*CheckTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTransaction not implemented")
}
func (UnimplementedStoreServiceServer) StreamBatchTransaction(StoreService_StreamBatchTransactionServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamBatchTransaction not implemented")
}
func (UnimplementedStoreServiceServer) StreamTransaction(StoreService_StreamTransactionServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTransaction not implemented")
}
func (UnimplementedStoreServiceServer) ListBalance(context.Context, *ListBalanceRequest) (*ListBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBalance not implemented")
}
func (UnimplementedStoreServiceServer) StreamCheckTransaction(StoreService_StreamCheckTransactionServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamCheckTransaction not implemented")
}
func (UnimplementedStoreServiceServer) SendBatchTransaction(context.Context, *SendBatchTransactionRequest) (*SendBatchTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBatchTransaction not implemented")
}
func (UnimplementedStoreServiceServer) mustEmbedUnimplementedStoreServiceServer() {}

// UnsafeStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServiceServer will
// result in compilation errors.
type UnsafeStoreServiceServer interface {
	mustEmbedUnimplementedStoreServiceServer()
}

func RegisterStoreServiceServer(s grpc.ServiceRegistrar, srv StoreServiceServer) {
	s.RegisterService(&StoreService_ServiceDesc, srv)
}

func _StoreService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_CreateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_Credit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Credit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_Credit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Credit(ctx, req.(*CreditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_Debit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Debit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_Debit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Debit(ctx, req.(*DebitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetUserBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetUserBalance(ctx, req.(*GetUserBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_CheckTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).CheckTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_CheckTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).CheckTransaction(ctx, req.(*CheckTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_StreamBatchTransaction_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StoreServiceServer).StreamBatchTransaction(&storeServiceStreamBatchTransactionServer{stream})
}

type StoreService_StreamBatchTransactionServer interface {
	Send(*StreamBatchTransactionResponse) error
	Recv() (*StreamBatchTransactionRequest, error)
	grpc.ServerStream
}

type storeServiceStreamBatchTransactionServer struct {
	grpc.ServerStream
}

func (x *storeServiceStreamBatchTransactionServer) Send(m *StreamBatchTransactionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storeServiceStreamBatchTransactionServer) Recv() (*StreamBatchTransactionRequest, error) {
	m := new(StreamBatchTransactionRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StoreService_StreamTransaction_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StoreServiceServer).StreamTransaction(&storeServiceStreamTransactionServer{stream})
}

type StoreService_StreamTransactionServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*StreamTransactionRequest, error)
	grpc.ServerStream
}

type storeServiceStreamTransactionServer struct {
	grpc.ServerStream
}

func (x *storeServiceStreamTransactionServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storeServiceStreamTransactionServer) Recv() (*StreamTransactionRequest, error) {
	m := new(StreamTransactionRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StoreService_ListBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListBalance(ctx, req.(*ListBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_StreamCheckTransaction_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StoreServiceServer).StreamCheckTransaction(&storeServiceStreamCheckTransactionServer{stream})
}

type StoreService_StreamCheckTransactionServer interface {
	Send(*StreamCheckTransactionResponse) error
	Recv() (*StreamCheckTransactionRequest, error)
	grpc.ServerStream
}

type storeServiceStreamCheckTransactionServer struct {
	grpc.ServerStream
}

func (x *storeServiceStreamCheckTransactionServer) Send(m *StreamCheckTransactionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storeServiceStreamCheckTransactionServer) Recv() (*StreamCheckTransactionRequest, error) {
	m := new(StreamCheckTransactionRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StoreService_SendBatchTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBatchTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).SendBatchTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_SendBatchTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).SendBatchTransaction(ctx, req.(*SendBatchTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoreService_ServiceDesc is the grpc.ServiceDesc for StoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend.store.api.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _StoreService_CreateAccount_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _StoreService_Reset_Handler,
		},
		{
			MethodName: "Credit",
			Handler:    _StoreService_Credit_Handler,
		},
		{
			MethodName: "Debit",
			Handler:    _StoreService_Debit_Handler,
		},
		{
			MethodName: "GetUserBalance",
			Handler:    _StoreService_GetUserBalance_Handler,
		},
		{
			MethodName: "CheckTransaction",
			Handler:    _StoreService_CheckTransaction_Handler,
		},
		{
			MethodName: "ListBalance",
			Handler:    _StoreService_ListBalance_Handler,
		},
		{
			MethodName: "SendBatchTransaction",
			Handler:    _StoreService_SendBatchTransaction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBatchTransaction",
			Handler:       _StoreService_StreamBatchTransaction_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamTransaction",
			Handler:       _StoreService_StreamTransaction_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamCheckTransaction",
			Handler:       _StoreService_StreamCheckTransaction_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "store/api.proto",
}
